<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Rest\Module'						=> __DIR__ . '/Module.php',
    'Rest\Controller\ClientController'	=> __DIR__ . '/src/Rest/Controller/ClientController.php',
    'Rest\Restful\RestfulController'    => __DIR__ . '/src/Rest/Controller/RestfulController.php',
);